<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnableDefaultItems>false</EnableDefaultItems>
        <TUnitImplicitUsings>disable</TUnitImplicitUsings>
        <TUnitAssertionsImplicitUsings>disable</TUnitAssertionsImplicitUsings>
        <TUnitMockImplicitUsings>disable</TUnitMockImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MorseCode.Collections.ValueEquality.UnitTests</RootNamespace>
        <Title>Value Equality Collections</Title>
        <Authors>MorseCode Software LLC</Authors>
        <Description>Unit tests for MorseCode.Collections.ValueEquality.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="1.64.13"/>
        <PackageReference Include="TUnit.Mocks" Version="1.65.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MorseCode.Collections.ValueEquality\MorseCode.Collections.ValueEquality.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="FrozenDictionaryWithValueEqualityTests.cs"/>
        <Compile Include="FrozenListWithValueEqualityTests.cs"/>
        <Compile Include="FrozenQueueWithValueEqualityTests.cs"/>
        <Compile Include="FrozenSetWithValueEqualityTests.cs"/>
        <Compile Include="FrozenStackWithValueEqualityTests.cs"/>
        <Compile Include="GlobalSetup.cs" />
        <Compile Include="ImmutableDictionaryWithValueEqualityTests.cs"/>
        <Compile Include="ImmutableListWithValueEqualityTests.cs"/>
        <Compile Include="ImmutableQueueWithValueEqualityTests.cs"/>
        <Compile Include="ImmutableSetWithValueEqualityTests.cs"/>
        <Compile Include="ImmutableStackWithValueEqualityTests.cs"/>
        <Compile Include="ReadOnlyDictionaryWithValueEqualityTests.cs"/>
        <Compile Include="ReadOnlyListWithValueEqualityTests.cs"/>
        <Compile Include="ReadOnlyQueueWithValueEqualityTests.cs"/>
        <Compile Include="ReadOnlySetWithValueEqualityTests.cs"/>
        <Compile Include="ReadOnlyStackWithValueEqualityTests.cs"/>
    </ItemGroup>

</Project>
